name: Create Workload Repository

on:
  workflow_call:
    inputs:
      environment-type:
        description: "Environment"
        required: true
        type: string
      role:
        description: "Role"
        required: true
        type: string
      counter:
        description: "Counter"
        required: true
        type: string        
      description:
        description: "Description"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  create-workload-repository:
    name: "Create Workload Repository"
    runs-on: ubuntu-latest

    outputs:
      repository-url: ${{ steps.create_repo.outputs.repo_url }}
  
    steps:
        # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    
    - name: Zero Pad
      run: echo "PADDED_COUNTER=$(printf '%03d' ${{ github.event.inputs.counter }})" >> $GITHUB_ENV

    # Use GitHub App to authorize repository actions
    - name: GitHub Authorization
      uses: actions/create-github-app-token@v1
      id: app_token
      with: 
        app-id: ${{ vars.PFIKEST_REPOSITORY_MANAGER_ID }}
        private-key: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_SECRET }}
        # optional: owner not needed IF the app has access to the repo running the workflow
        #   if you get 'RequestError [HttpError]: Not Found 404', pass in owner
        owner: ${{ github.repository_owner }}
      
    - name: Create Repository
      id: create_repo
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/PfikestInt/WorkloadTemplate/generate \
          -d '{"owner":"PfikestInt","name":"rg-${{ github.event.inputs.environment-type }}-${{ github.event.inputs.role }}-${{ env.PADDED_COUNTER }}","description":"${{ github.event.inputs.description }}","include_all_branches":true,"private":false}' > results.json
        echo "repo_url=$(jq '.html_url' results.json)" >> $GITHUB_OUTPUT
