name: "Create Workload"

on:
  workflow_dispatch: # Allow manual triggering
    inputs:
      subscription:
        description: "Subscription"
        required: true
        type: choice
        options:
        - "Azure subscription 1"
        - "sysadmin_sandbox"
        - "signature-development-001"
        - "signature-corp-shared-001"
      environment-type:
        description: "Environment"
        required: true
        type: choice
        options:
        - "sb"
        - "d"
        - "t"
        - "s"
        - "p"
        - "np"
      role:
        description: "Role"
        required: true
        type: string
      counter:
        description: "Counter"
        required: true
        default: '1'
        type: string        
      description:
        description: "Description"
        required: true
        type: string

permissions:
  id-token: write
  contents: write
        
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  create-workload-repository:
    name: "Create Repository"
    needs: checkout
    uses: ./.github/workflows/create_workload_repository.yml
    with:
      environment-type: environment-type
      role: role
      counter: counter
      description: description
    secrets: inherit

  create-config:
    name: "Create Config"
    runs-on: ubuntu-latest
    needs: create-workload-repository

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Config
        run: echo "${{ needs.create-workload-repository.outputs.repository-url }}"
    
  update-history:
    name: "Update History"
    needs: create-config
    uses: ./.github/workflows/update_workload_history.yml
    with:
      environment-type: environment-type
      role: role
      counter: counter
      description: description
    secrets: inherit
