name: Create Workload Repository

on:
  workflow_call:
    inputs:
      environment-type:
        required: true
        type: string
      role:
        required: true
        type: string
      counter:
        required: true
        type: string        
      description:
        required: true
        type: string
    secrets:
      PFIKEST_REPOSITORY_MANAGER_SECRET:
        required: true
      PFIKEST_REPOSITORY_MANAGER_ID:
        required: true
    outputs:
      repository-url: ${{ jobs.create_workload_repository.outputs.repository-url }}

permissions:
  id-token: write
  contents: read

jobs:
  create_workload_repository:
    name: "Create Workload Repository"
    runs-on: ubuntu-latest

    outputs:
      repository-url: ${{ steps.create_repo.outputs.REPO_URL }}
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Zero Pad
      run: echo "PADDED_COUNTER=$(printf '%03d' ${{ github.event.inputs.counter }})" >> $GITHUB_ENV

    - name: GitHub Authorization
      uses: actions/create-github-app-token@v1
      id: app_token
      with: 
        app-id: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_ID }}
        private-key: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_SECRET }}
        owner: ${{ github.repository_owner }}
      
    - name: Create Repository
      id: create_repo
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/PfikestInt/WorkloadTemplate/generate \
          -d '{"owner":"PfikestInt","name":"rg-${{ github.event.inputs.environment-type }}-${{ github.event.inputs.role }}-${{ env.PADDED_COUNTER }}","description":"${{ github.event.inputs.description }}","include_all_branches":true,"private":false}' > results.json
        echo "REPO_URL=$(jq '.html_url' results.json)" >> "$GITHUB_OUTPUT"

    - run: echo "${{ steps.create_repo.outputs.REPO_URL }}"
    