name: "Create Workload"

on:
  workflow_dispatch: # Allow manual triggering
    inputs:
      subscription:
        description: "Subscription"
        required: true
        type: choice
        options:
        - "Azure subscription 1"
        - "sysadmin_sandbox"
        - "signature-development-001"
        - "signature-corp-shared-001"
      environment-type:
        description: "Environment"
        required: true
        type: choice
        options:
        - "sb"
        - "d"
        - "t"
        - "s"
        - "p"
        - "np"
      role:
        description: "Role"
        required: true
        type: string
      counter:
        description: "Counter"
        required: true
        default: '1'
        type: string        
      description:
        description: "Description"
        required: true
        type: string

permissions:
  id-token: write
  contents: write

env:
  SUBSCRIPTION: ${{ github.event.inputs.subscription }}
  ENVIRONMENT: ${{ github.event.inputs.environment-type }}
  ROLE: ${{ github.event.inputs.role}}
  COUNTER: ${{ github.event.inputs.counter }}
  DESCRIPTION: ${{ github.event.inputs.description }}

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: GitHub Authorization
        uses: actions/create-github-app-token@v1
        id: app_token
        with: 
          app-id: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_ID }}
          private-key: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_SECRET }}
          owner: ${{ github.repository_owner }}
      
      - name: Create Repository
        env:
          AUTH_TOKEN: ${{ steps.app_token.outputs.token }}
        run: python -m script.create_workload_repository
      
      - name: Hello
        run: echo "Hello"

  # create-workload-repository:
  #   name: "Create Repository"
  #   needs: checkout
  #   uses: ./.github/workflows/sub_create_workload_repository.yml
  #   with:
  #     environment-type: environment-type
  #     role: role
  #     counter: counter
  #     description: description
  #   secrets: inherit

  # create-config:
  #   name: "Create Workload Config"
  #   needs: create-workload-repository
  #   uses: ./.github/workflows/sub_create_workload_config.yml
  #   with:
  #     environment-type: environment-type
  #     role: role
  #     counter: counter
  #     description: description
  #     repository_url: ${{ needs.create-workload-repository.outputs.repository-url }}
  #   secrets: inherit
    
  # update-history:
  #   name: "History"
  #   needs: create-config
  #   uses: ./.github/workflows/sub_update_workload_history.yml
  #   with:
  #     environment-type: environment-type
  #     role: role
  #     counter: counter
  #     description: description
  #   secrets: inherit
