name: "Create Resource Group"

on:
  workflow_dispatch: 
    inputs:
      subscription:
        description: Subscription
        required: true
        type: choice
        options:
        - "AzureSubscription1"
      repository_name:
        description: "Repository Name"
        required: true
        type: string
      environment_type:
        description: "Environment"
        required: true
        type: choice
        options:
        - "sb"
        - "d"
        - "t"
        - "s"
        - "p"
        - "np"
      role:
        description: "Role"
        required: true
        type: string
      counter:
        description: "Counter"
        required: true
        default: '1'
        type: string        
      description:
        description: "Description"
        required: true
        type: string

permissions:
  id-token: write
  contents: write

env:
  SUBSCRIPTION: ${{ github.event.inputs.subscription }}
  ENVIRONMENT: ${{ github.event.inputs.environment_type }}
  ROLE: ${{ github.event.inputs.role}}
  COUNTER: ${{ github.event.inputs.counter }}
  DESCRIPTION: ${{ github.event.inputs.description }}

jobs:
  validate_rg_does_not_exists:
    name: Validate Resource Group
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: secrets.AZURE_CLIENT_ID
          tenant-id: "d3994d90-925b-4938-badd-e17aed9acc0a"
          subscription-id: "46b82283-ba32-4501-a19e-7b75892faf7f"

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
  
  # create_workload_repository:
  #   name: Create Repository
  #   runs-on: ubuntu-latest

  #   outputs:
  #     repository-url: ${{ steps.create_repo.outputs.REPO_URL }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Zero Pad
  #       run: echo "PADDED_COUNTER=$(printf '%03d' ${{ env.COUNTER }})" >> $GITHUB_ENV

  #     - name: GitHub Authorization
  #       uses: actions/create-github-app-token@v1
  #       id: app_token
  #       with: 
  #         app-id: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_ID }}
  #         private-key: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_SECRET }}
  #         owner: ${{ github.repository_owner }}
        
  #     - name: Create Repository
  #       if: ${{ env.PADDED_COUNTER != '' && env.PADDED_COUNTER != '000'}}
  #       id: create_repo
  #       run: |
  #         curl -L \
  #           -X POST \
  #           -H "Accept: application/vnd.github+json" \
  #           -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" \
  #           -H "X-GitHub-Api-Version: 2022-11-28" \
  #           https://api.github.com/repos/PfikestInt/WorkloadTemplate/generate \
  #           -d '{"owner":"PfikestInt","name":"rg-${{ env.ROLE }}-${{ env.PADDED_COUNTER }}","description":"${{ env.DESCRIPTION }}","include_all_branches":true,"private":false}' > results.json && \
  #         export REPO_URL=$(jq '.html_url' results.json)
  #         echo "Created: ${REPO_URL}"
