name: "Create Workload"

on:
  workflow_dispatch: # Allow manual triggering
    inputs:
      workload-name:
        description: "Workload name"
        required: true
        type: string
      description:
        description: "Description"
        required: true
        type: string
  
jobs:
  create-workload:
    name: "Create Workload"
    runs-on: ubuntu-latest
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      
      # Use GitHub App to authorize repository actions
      - name: Authorize
        uses: actions/create-github-app-token@v1
        id: app-token
        with: 
          app-id: ${{ vars.PFIKEST_REPOSITORY_MANAGER_ID }}
          private-key: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_SECRET }}
          # optional: owner not needed IF the app has access to the repo running the workflow
          #   if you get 'RequestError [HttpError]: Not Found 404', pass in owner
          # owner: ${{ github.repository_owner }}

      - name: Create
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/PfikestInt/WorkloadTemplate/generate \
            -d '{"owner":"PfikestInt","name":"${{ github.event.inputs.workload-name }}","description":"${{ github.event.inputs.description }}","include_all_branches":true,"private":false}'

      