name: "Create Workload Repository"

on:
  workflow_dispatch:
    inputs:
      description:
        description: "Description"
        required: true
        type: string
      role:
        description: "Role"
        required: true
        type: string
      counter:
        description: "Counter"
        required: true
        default: '1'
        type: string

permissions:
  id-token: write
  contents: write

env:
  ROLE: ${{ github.event.inputs.role}}
  COUNTER: ${{ github.event.inputs.counter }}
  DESCRIPTION: ${{ github.event.inputs.description }}

jobs:
  create_workload_repository:
    name: Create Repository
    runs-on: ubuntu-latest

    outputs:
      repository-url: ${{ steps.create_repo.outputs.REPO_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zero Pad
        run: echo "PADDED_COUNTER=$(printf '%03d' ${{ env.COUNTER }})" >> $GITHUB_ENV

      - name: GitHub Authorization
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_ID }}
          private-key: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_SECRET }}
          owner: ${{ github.repository_owner }}

      - name: Create Repository
        if: ${{ env.PADDED_COUNTER != '' && env.PADDED_COUNTER != '000'}}
        id: create_repo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository_owner }}/WorkloadTemplate/generate \
            -d '{"owner":"PfikestInt","name":"terraform-rg-${{ env.ROLE }}-${{ env.PADDED_COUNTER }}","description":"${{ env.DESCRIPTION }}","include_all_branches":true,"private":false}' > results.json && \
          export REPO_URL=$(jq '.html_url' results.json)
          echo "Created: ${REPO_URL}"
