name: Sub Create Workload Config

on:
  workflow_call:
    inputs:
      environment-type:
        required: true
        type: string
      role:
        required: true
        type: string
      counter:
        required: true
        type: string        
      description:
        required: true
        type: string
      repository_url:
        required: true
        type: string
    secrets:
      PFIKEST_REPOSITORY_MANAGER_SECRET:
        required: true
      PFIKEST_REPOSITORY_MANAGER_ID:
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  create-workload-config:
      name: "Create Config"
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Zero Pad
          run: echo "FINAL_SEGMENTS=$(echo "$url" | awk -F'/' '{print $(NF-1)"/"$(NF)}')" >> $GITHUB_ENV
            
        - name: GitHub Authorization
          uses: actions/create-github-app-token@v1
          id: app_token
          with: 
            app-id: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_ID }}
            private-key: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_SECRET }}
            owner: ${{ github.repository_owner }}
          
        - name: Checkout New Repository
          uses: actions/checkout@v4
          with:
            repository: ${{ env.FINAL_SEGMENTS }}
            path: new_repo
          
        - name: Check
          run: echo ${{ github.event.inputs.repository_url }}
        
        - name: Install Requirements
          run: ls new_repo
